### ISSUE TITLE
xpocket有没有在云原生方面的思考？

### ISSUE THREAD

**Issue by manheiba** [PerfMa/xpocket#1]
占个楼，提几个问题:
1、xpocket在云原生中如何定位？ 云原生的可观测性包括：指标、日志、追踪，xpocket在这三方面后面有什么规划吗？
2、对于生产级“动态开启性能分析”这种特性，有什么规划吗？例如，在某些指标异常场景下，开启自动诊断，输出一些报告等。
3、有没有和serviceMesh整合的想法，有计划出控制面产品吗？

**Comment by dawsongzhao** [comment]
看了19:30的发布会，被两位帅气的技术达人征服了，感谢开源这么好的产品。
与楼上有类似疑问：
1、xpocket如何应对分布式集群系统的性能指标分析、诊断调优？
2、性能优化的前提是监控到性能有瓶颈，如何提供全链路的性能监控、诊断套件及解决方案。与Skywalking这类产品是否有结合点？
3、个人工作领域在大数据领域，对于大数据生态组件，是否有套装解决方案？
4、性能对于技术选型有较好的辅助作用，是否可以构建一个社区或者生态，分享交流各种环境下的性能测试、benchmark测试方案、方法、思路、结果，形成专家知识库？

**Comment by PerfRocket** [comment]
楼上两位的问题我统一回复一下：
1. 对于云原生、分布式集群和ServiceMesh：XPocket本身并不会去规划具体的业务功能，而是去规划为了实现某些具体业务插件而需要的基础框架能力；所以针对这几个场景，XPocket其实是有规划去通过UIEngine的扩展来实现不同角色的XPocket实例，例如XPocket-Agent、XPocket-ServerSide以及对应的XPocket-Manager，通过这写角色间建立的数据通道和各自包含的插件来实现具体的业务功能。
2. 针对性能瓶颈的监控和定位，XPocket的规划大概会分为两个层面：第一是性能数据的收集，这一部分就会依赖现有的大量工具来搭建和完善，包括但不限于pinpoint、skywalking、jfr与bpf等数据采集的工具；第二方面是基于元信息的分析和定位，在基于构建好的元信息的基础之上，大家可以根据各自的经验自由的构建分析算法模型去做问题的定位；XPocket的规划旨在解耦这两部分，让最专业的人去做最专业的事。
3. 对于生产级的动态监控诊断同样也是由插件来实现的，XPocket为了更好的适配这类插件会去做统一的生命周期管理和触发模式的定义。
4. 目前没有对ServiceMesh与控制面产品以及大数据方向的规划，但是也很欢迎大家有好的方法可以开发相应的插件并分享，如果对XPocket主体框架有需要支持的需求，也欢迎提交issue或者直接提交pr。
5. 社区的话，目前XPocket就是打算去构建一个完整的生态的，结合github, XPocket官方网站: https://xpocket.perfma.com XPocket插件中心: https://plugin.xpocket.perfma.com OutOfMemory社区： https://club.perfma.com  XPocket希望构建一个完整、高效的交流与分享生态圈，借助社区与开发者来强化XPocket能够解决问题的能力与范围

**Comment by ferdiknight** [comment]
楼上两位的问题我统一回复一下：

对于云原生、分布式集群和ServiceMesh：XPocket本身并不会去规划具体的业务功能，而是去规划为了实现某些具体业务插件而需要的基础框架能力；所以针对这几个场景，XPocket其实是有规划去通过UIEngine的扩展来实现不同角色的XPocket实例，例如XPocket-Agent、XPocket-ServerSide以及对应的XPocket-Manager，通过这写角色间建立的数据通道和各自包含的插件来实现具体的业务功能。
针对性能瓶颈的监控和定位，XPocket的规划大概会分为两个层面：第一是性能数据的收集，这一部分就会依赖现有的大量工具来搭建和完善，包括但不限于pinpoint、skywalking、jfr与bpf等数据采集的工具；第二方面是基于元信息的分析和定位，在基于构建好的元信息的基础之上，大家可以根据各自的经验自由的构建分析算法模型去做问题的定位；XPocket的规划旨在解耦这两部分，让最专业的人去做最专业的事。
对于生产级的动态监控诊断同样也是由插件来实现的，XPocket为了更好的适配这类插件会去做统一的生命周期管理和触发模式的定义。
目前没有对ServiceMesh与控制面产品以及大数据方向的规划，但是也很欢迎大家有好的方法可以开发相应的插件并分享，如果对XPocket主体框架有需要支持的需求，也欢迎提交issue或者直接提交pr。
社区的话，目前XPocket就是打算去构建一个完整的生态的，结合github, XPocket官方网站: https://xpocket.perfma.com XPocket插件中心: https://plugin.xpocket.perfma.com OutOfMemory社区： https://club.perfma.com XPocket希望构建一个完整、高效的交流与分享生态圈，借助社区与开发者来强化XPocket能够解决问题的能力与范围

@dawsongzhao @manheiba
