### ISSUE TITLE
没太看懂主要作用是什么，建议可以加一些最佳实践的文章

### ISSUE THREAD

**Issue by farmerjohngit** [PerfMa/xpocket#2]
没有看直播，单看文档描述像是把一堆开源工具组合成了一个工具箱？

**Comment by RecursionHs** [comment]
> 没有看直播，单看文档描述像是把一堆开源工具组合成了一个工具箱？

就是这个意思，他们不是自己也有个工具嘛。

**Comment by ferdiknight** [comment]
XPocket本身的初衷并不是靠自身去解决问题，而是构建一个框架，可以集合现有工具，也可以快速的去定制化目前工具的一些能力，通过插件的完善和整合来强化XPocket的能力，后续我们也会去分享各类通过XPocket结合各类插件来解决问题的最佳实践，形式不限于文章、视频等，也尽情关注 https://xpocket.perfma.com 与 https://club.perfma.com

**Comment by jacky-lk** [comment]
有和apm工具整合的规划吗？如果只是命令行这种，对于云上应用效果差些

**Comment by ferdiknight** [comment]
@jacky-lk 跟apm工具整合是在计划中的，后续我们就会开始XPocket多角色模式运行的研发工作，主要就是适配多实例部署与管理的支持
