### ISSUE TITLE
希望可以增加一些命令行界面的支持，如窗口尺寸、绘制等工具包

### ISSUE THREAD

**Issue by kongwu-** [PerfMa/xpocket#28]
由于某些工具并不是为命令行设计的，为了更好的使用体验，往往需要自己实现渲染逻辑。但 XPocket 没有提供命令行绘制的支持，只能自己在插件内完成，比较麻烦。

希望 XPocket 可以增强对命令行绘制的支持，提供以下功能：
1. 命令行窗口尺寸，宽、高，窗口大小改变的事件（如果有）
2. 颜色、表格、列表的支持，边距、颜色、字体大小等（可以考虑直接集成 CRaSH，做一些 XPocket 的封装）

**Comment by ferdiknight** [comment]
在以下两个需求中完成上述功能支持
#30 
#31
