### ISSUE TITLE
插件 Jar 包内存在一些没有引用的代码（servlet api），但在插件启动的时候会直接 NoClassDefoundError。ClassLoader  应该是按需加载的，没有执行的代码不应该报错

### ISSUE THREAD

**Issue by kongwu-** [PerfMa/xpocket#29]
插件内引用了一个 hsqldb 的包，该依赖内存在 servlet api的代码，可在运行时并没有执行到相关代码。

在打包成插件运行在 XPocket 时会直接报错， NoClassDefoundError ，这是不是 XPocket ClassLoader 机制问题呢？还没有执行到的代码，为什么会触发解析呢？

**Comment by ferdiknight** [comment]
目前如果你没有在xpocket.def定义文件中配置plugin-command-package该属性定义插件命令的实现包，那么框架会去扫描整个jar包来确定有哪些命令定义，所以就会去加载那些类来获取注解，就会触发这个问题了，这个暂时无解，建议定义plugin-command-package属性以提升插件的加载速度，与规避无效的类加载

**Comment by kongwu-** [comment]
还有`plugin-command-package`这个参数呢，我回去加上试试
