### ISSUE TITLE
Homebrew will not run wget command (Library not loaded)

### ISSUE THREAD

**Issue by sangshy-go** [PerfMa/xpocket#3]
下载模拟程序和下载xpocket，执行`wget https://xxxx`，出现如下异常：
`dyld: Library not loaded: /usr/local/opt/gettext/lib/libintl.1.0.dylib
  Referenced from: /usr/local/bin/wget
  Reason: image not found`

解决办法：`brew reinstall wget`

**Comment by ferdiknight** [comment]
确认下，是在macOS上运行wget下载程序报错还是在XPocket交互命令行中运行wget报错？

**Comment by sangshy-go** [comment]
> 确认下，是在macOS上运行wget下载程序报错还是在XPocket交互命令行中运行wget报错？

MacOS下，跟本地wget安装有关。

**Comment by ferdiknight** [comment]
ok,确认不是XPocket本身的问题，那我就先关闭该issue了噢~
