### ISSUE TITLE
[Compile failure]: Maybe this jar forgot to upload to the central repository?  “com.perfma.xlab:xpocket-jline” 

### ISSUE THREAD

**Issue by BillLucky** [PerfMa/xpocket#43]
Maven build info
> [WARNING] The POM for com.perfma.xlab:xpocket-jline:jar:2.1.0-RELEASE is missing, no dependency information available

JAR：https://mvnrepository.com/artifact/com.perfma.xlab
![image](https://user-images.githubusercontent.com/8528590/220279621-3f7a68de-d75c-4ebd-9348-c44ff04fd805.png)

If this jar package is uploaded to the central warehouse, it can help developers compile successful projects.

**Comment by ferdiknight** [comment]
Hello, sorry for this failure. [com.perfma.xlab:xpocket-jline] this is a inner module of the project. But we set a wrong version of this module (2.1.0-RELEASE expect : 2.1.1-RELEASE). We are going to fix this problem. I will update this issue when we are haven done. Thanks for reporting.

**Comment by BillLucky** [comment]
best wishes to the community  😁

**Comment by ferdiknight** [comment]
fix this problem
