### ISSUE TITLE
[Bug]: 由于系统属性的缺失，导致IDEA中直接启动main方法异常

### ISSUE THREAD

**Issue by DearZh** [PerfMa/xpocket#45]
默认情况下Xpocket所提供的bat/sh脚本中由于已经添加了对应的系统参数，所以使用脚本启动是一切正常的。

但当直接在IDEA中启动main方法时，由于缺失系统参数，所以将导致产生如下异常：

![image](https://user-images.githubusercontent.com/32116870/222943146-93dc6a80-720f-470f-9503-b249f72e3592.png)

**Comment by DearZh** [comment]
哦豁，让我来修复掉它 😀

**Comment by ferdiknight** [comment]
feature completed
