### ISSUE TITLE
slow sql log 可视化

### ISSUE THREAD

**Issue by aaafenghao** [PerfMa/xpocket#52]
有慢sql日志可视化插件么

**Comment by DearZh** [comment]
可以来这里找一下是否有你需要的插件：https://plugin.xpocket.perfma.com/plugin

另外，插件的研发并不复杂，如果没有合适的，欢迎贡献一个插件。

插件开发的方式看这里：https://xpocket.perfma.com/docs/developer/#%E6%8F%92%E4%BB%B6%E5%BC%80%E5%8F%91
