### ISSUE TITLE
rancher 进入控制台，无法显示当前输入内容

### ISSUE THREAD

**Issue by youzipi** [PerfMa/xpocket#8]
rancher = v2.5.3
k8s = v1.18.9-eks-d1db3c

```bash
// 应该显示：
XPocket [system] > plugins
// 实际显示：
>....
```

![image](https://user-images.githubusercontent.com/5629307/108688279-af9c4200-7532-11eb-808e-e123df7921c9.png)

**Comment by ferdiknight** [comment]
这个环境组合我们确实还没验证过，我搞个环境试一下。感谢反馈。

**Comment by youzipi** [comment]
环境升级之后，没有这个问题了。
rancher = v2.5.7
k8s =  v1.18.20-eks-8c579e

xpocket 版本和之前一样，2.0.0

**Comment by ferdiknight** [comment]
这个问题应该是rancher 2.5.3版本terminal的输入输出的兼容性问题，建议可以在容器内启动telnet server模式，然后在其他网络联通的机器使用telnet连接后操作，该模式目前还未release，可以使用 https://github.com/PerfMa/xpocket/tree/iteration/2.1.1-RELEASE  该分支的代码build后使用 xpocket.sh -run_mode telnet -port 9527 启动telnet server模式；也可以等待我们release该版本
